JuliaStats/LogExpFunctions.jl

src/basicfuns.jl, test/basicfuns.jl
parameterize softmax to be usable with AD.
=> Update softmax with parameterization

Project.toml, src/LogExpFunctions.jl, src/basicfuns.jl, test/basicfuns.jl, test/runtests.jl
This PR fixes https://github.com/JuliaStats/LogExpFunctions.jl/issues/12. Additionally, it allows to use `softmax` and `softmax!` with `CuArray`s (tested locally but not included in the testset).
=> Allow general indices in `softmax!`

Project.toml, docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/index.md, src/LogExpFunctions.jl, src/basicfuns.jl, src/constants.jl
The constants in StatsFuns were moved to [IrrationalConstants](https://github.com/JuliaMath/IrrationalConstants.jl) such that other packages such as e.g. SpecialFunctions or DiffRules can make use of them without having to depend on StatsFuns. This PR ~~reexports the logarithmic constants in IrrationalConstants and~~ updates the documentation (also adds a missing docstring for `logsubexp` and fixes doctests which could be moved to a separate PR).
**Edit:** This PR removes the definition of the logarithmic constants in LogExpFunctions and uses the definitions in IrrationalConstants instead but does not reexport the constants defined in IrrationalConstants. Users and downstream packages should depend on IrrationalConstants directly.
=> Use IrrationalConstants and do not export logarithmic constants

src/basicfuns.jl
In benchmarks of https://github.com/JuliaStats/StatsBase.jl/pull/714 and the examples shown below it seems that on my computer the ternary operator is sometimes faster than `ifelse` (which evaluates all branches) and never slower:
With the latest release:
```julia
julia> using LogExpFunctions, BenchmarkTools, Random
julia> Random.seed!(1234);
julia> out = Vector{Float64}(undef,100_000);
julia> x, y = rand(100_000), rand(100_000);
julia> @btime map!(xlogx, $out, $x);
717.358 μs (0 allocations: 0 bytes)
julia> @btime map!(xlogy, $out, $x, $y);
780.322 μs (0 allocations: 0 bytes)
julia> @btime map!(logistic, $out, $x);
745.426 μs (0 allocations: 0 bytes)
julia> @btime map!(logaddexp, $out, $x, $y);
2.502 ms (0 allocations: 0 bytes)
julia> @btime sum(xlogx, $x); # similar to …
```
=> Use ternary operator instead of ifelse

Project.toml, src/LogExpFunctions.jl, src/chainrules.jl, test/chainrules.jl, test/runtests.jl
This PR adds ChainRules definitions for the derivatives of the functions in LogExpFunctions.
Currently, Zygote contains some reverse-mode differentiation rules for LogExpFunctions (https://github.com/FluxML/Zygote.jl/blob/master/src/lib/logexpfunctions.jl) but it does not cover all functions in the package and is Zygote-specific, i.e., it is not used by any other AD system. ChainRules allows us to define both forward- and reverse-mode derivatives (for all functions) in an AD system independent way. I think both the different AD backends and LogExpFunctions would benefit if a complete set of ChainRules definitions for LogExpFunctions would be added in a central Zygote-independent place.
Since ChainRulesCore 1 is a very lightweight package (see [@oxinabox's …
=> Add ChainRules definitions

Project.toml, docs/src/index.md, src/LogExpFunctions.jl, src/basicfuns.jl, src/chainrules.jl, test/basicfuns.jl, test/chainrules.jl
This PR adds `xlog1py(x, y) = x * log1p(y)` which handles `x == 0` in the same way as `xlogx` and `xlogy`.
The function is useful e.g. if one implements the log pdf of the Beta distribution and tries to avoid `NaN` values at `x = 1` for parameter `beta = 1`.
=> Add `xlog1py`

Project.toml, docs/Manifest.toml, src/basicfuns.jl, src/chainrules.jl, test/basicfuns.jl, test/chainrules.jl
This PR adds a `dims` keyword argument to `softmax` and `softmax!`. The current behaviour (normalizing the whole array and neglecting mismatching dimensions) is preserved with the default value `dims=:`.
The PR also removes the ChainRules definition for `softmax!` and instead adds one for `softmax` (with `dims` keyword argument). Apparently, currently no rules should be defined for mutating functions (https://juliadiff.org/ChainRulesCore.jl/stable/writing_good_rules.html#Which-functions-need-rules?), so this is a bugfix.
=> Add `dims` keyword argument to `softmax` and `softmax!`

Project.toml, docs/src/index.md, src/LogExpFunctions.jl, src/with_logabsdet_jacobian.jl, test/runtests.jl, test/with_logabsdet_jacobian.jl
This PR adds support for `ChangesOfVariables.test_with_logabsdet_jacobian` to functions in LogExpFunctions that already support `InverseFunctions.inverse`.
This complements #29: [InverseFunctions](https://github.com/JuliaMath/InverseFunctions.jl) and [ChangesOfVariables](https://github.com/JuliaMath/ChangesOfVariables.jl) were designed in tandem (both are extremely lightweight packages) to support variable transformations. Applications that perform variable transformations often need the volume element of the transformation in addition to the result and the inverse of the transformation. `ChangesOfVariables.with_logabsdet_jacobian(f, x)` delivers that capability, it returns the equivalent of `f(x), logabsdet(jacobian(f, x))`
With this PR, fun stuff like this works out of the box:
```julia …
```
=> Add support for ChangesOfVariables.with_logabsdet_jacobian

Project.toml, docs/src/index.md, src/LogExpFunctions.jl, src/basicfuns.jl, src/chainrules.jl, src/with_logabsdet_jacobian.jl, test/basicfuns.jl, test/chainrules.jl, test/with_logabsdet_jacobian.jl
This PRs adds an implementation of `log(cosh(x))`.
Fixes https://github.com/JuliaStats/LogExpFunctions.jl/issues/31.
cc @cossio
=> Add `logcosh`

Project.toml, docs/src/index.md, src/LogExpFunctions.jl, src/basicfuns.jl, src/chainrules.jl, test/basicfuns.jl, test/chainrules.jl, test/runtests.jl
Adds functions `xexpx(x)` and `xexpy(x, y)`, which compute `x * exp(x)` and `x * exp(y)`, respectively, but taking the "correct" limit when the exponent is infinite.
Close #15 .
=> xexpx, xexpy

Project.toml, docs/src/index.md, src/LogExpFunctions.jl, src/logsumexp.jl, test/basicfuns.jl
Alternative to https://github.com/JuliaStats/LogExpFunctions.jl/pull/38.
```julia
julia> using LogExpFunctions, BenchmarkTools
julia> @btime logsumexp(X; dims=1) setup=(X=500 .* randn(100_000, 100);); # master
86.982 ms (2 allocations: 2.64 KiB)
julia> @btime logsumexp(X; dims=2) setup=(X=500 .* randn(100_000, 100);); # master
109.627 ms (8 allocations: 2.29 MiB)
julia> @btime logsumexp!(r, X) setup=(r=randn(1,100); X=500 .* randn(100_000, 100);); # this PR
85.421 ms (1 allocation: 1.77 KiB)
julia> @btime logsumexp!(r, X) setup=(r=randn(100_000, 1); X=500 .* randn(100_000, 100);); # this PR
110.363 ms (2 allocations: 1.53 MiB)
```
~~Needs tests.~~
I added tests.
=> Add `logsumexp!`

Project.toml, src/logsumexp.jl, test/basicfuns.jl
This PR fixes
```julia
julia> out = [missing, 1.0];
julia> x = rand(2, 4);
julia> logsumexp!(out, x)
ERROR: MethodError: no method matching logsumexp!(::Vector{Union{Missing, Float64}}, ::Matrix{Float64})
Closest candidates are:
logsumexp!(::AbstractArray{<:Number}, ::AbstractArray{<:Number}) at ~/.julia/dev/LogExpFunctions/src/logsumexp.jl:45
Stacktrace:
[1] top-level scope
@ REPL[8]:1
```
and adds support for output arrays with abstract `eltype`s, similar to e.g. `sum!`:
```julia
julia> sum!(out, x)
2-element Vector{Union{Missing, Float64}}:
1.2939717364740972
2.348547173687184
```
=> Fix `logsumexp!` with output arrays of abstract `eltype`

test/basicfuns.jl
This would have caught the issues I mentioned in https://github.com/JuliaStats/LogExpFunctions.jl/pull/41. I checked that the tests do not pass with the implementation in that PR.
=> Check type stability and return type of `logaddexp`

Project.toml, src/basicfuns.jl, test/basicfuns.jl
Motivated by the approach in https://github.com/JuliaStats/LogExpFunctions.jl/pull/41, this PR adds an additional branch to `log1pexp` that improves performance for large negative numbers for which `iszero(log1pexp(x))` (in floating point arithmetic).
This avoids an `exp` call which improves performance:
On the master branch:
```julia
julia> using LogExpFunctions, BenchmarkTools
julia> x = -1_000.0;
julia> @btime log1pexp($x);
4.289 ns (0 allocations: 0 bytes)
julia> x = -40.0;
julia> @btime log1pexp($x);
3.861 ns (0 allocations: 0 bytes)
julia> x = 0.0;
julia> @btime log1pexp($x);
12.676 ns (0 allocations: 0 bytes)
julia> x = 30.0;
julia> @btime log1pexp($x);
4.705 ns (0 allocations: 0 bytes)
julia> x = 40.0;
julia> @btime log1pexp($x);
1.295 ns (0 allocations: 0 bytes)
```
With this PR: …
=> Add threshold for zero results in `log1pexp`

Project.toml, src/basicfuns.jl, test/basicfuns.jl
This looks like it would make sense, given that the other functions dispatch on `Real` argument, and it also fixes #44.
=> Add fallbacks for `log1pmx` and `logmxp1`

Project.toml, src/chainrules.jl
Similar to the existing ChainRules definitions for `xexpx` and `xexpy`, and inspired by https://github.com/FluxML/Zygote.jl/blob/master/src/lib/logexpfunctions.jl, this PR improves the ChainRules definitions of `xlogx`, `xlogy`, and `xlog1py` by reusing intermediate results of the computation of the primal when calculating the partial derivatives.
=> Reuse intermediate result of primal in derivative

Project.toml, src/chainrules.jl, test/chainrules.jl, test/runtests.jl
Apologies for the new PR, but I accidentally deleted my remote branch. This replaces #54
=> Add iszero(x) branches to xlogy and xlog1py

Project.toml, src/logsumexp.jl, test/basicfuns.jl, test/runtests.jl
Fixes #59 on my computer.
Maybe you can confirm that @theogf?
=> Fix issues with ForwardDiff 0.10.33

Project.toml, ext/ChainRulesCoreExt.jl, ext/ChangesOfVariablesExt.jl, ext/InverseFunctionsExt.jl, src/LogExpFunctions.jl
By doing so, on Julia >= 1.9 support for these packages will be loaded only when the packages are loaded by the user (or some other package). Some more info about weak dependencies: https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)
The PR is based on https://github.com/JuliaMath/SpecialFunctions.jl/pull/421 and https://github.com/JuliaStats/StatsFuns.jl/pull/153.
=> Make ChainRulesCore, ChangesOfVariables, and InverseFunctions weak dependencies

ext/ChainRulesCoreExt.jl, ext/ChangesOfVariablesExt.jl
Due to https://github.com/JuliaLang/julia/issues/48533, it might have to be necessary to disable packages loading other dependencies other than their weak dependencies and the parent package. The rest of the packages have to be transitively loaded from the parent package. This does this fix for the packages loaded in the extensions.
cc @vtjnash
=> tweak how some packages are loaded in extensions

Project.toml, ext/LogExpFunctionsChainRulesCoreExt.jl, ext/LogExpFunctionsChangesOfVariablesExt.jl, ext/LogExpFunctionsInverseFunctionsExt.jl, src/LogExpFunctions.jl
- this will ensure extension names are unique
- whenever there is another package with same ext name, building sysimage fails
- ex: ChangeOfVariables has its own ChainRulesCoreExt.jl
Ex: https://github.com/SciML/DiffEqBase.jl/tree/master/ext follows this for above mentioned reasons
=> refactor: prefix extensions with package name

Project.toml, docs/src/index.md, ext/LogExpFunctionsChainRulesCoreExt.jl, src/LogExpFunctions.jl, src/basicfuns.jl, test/basicfuns.jl, test/chainrules.jl
closes #69 . Implementation, chainrules and tests done
=> add `logabssinh`

src/basicfuns.jl, test/basicfuns.jl
=> fix `xexpy(0, 1000)`

.github/dependabot.yml, .github/workflows/CI.yml, Project.toml, src/LogExpFunctions.jl, src/basicfuns.jl, test/basicfuns.jl
Since it turned out that tests fail with Julia 1.0.0 (Julia version installed with `min`), I update the Julia compat to 1.10, the current LTS.
=> Update CI setup, add dependabot, and update Julia compat to 1.10

src/basicfuns.jl, test/basicfuns.jl
Through some clever use of Remez.jl (and some testing to better limit where the fallback is appropriate), we can remove almost all of the branches from the Float64 implementation and add a similar (but slightly faster) Float32 version.
This PR needs some CI tests added before merging, but I believe the algorithm is correct at this point.
=> improve `log1pmx`, add `Float32` implimentation

src/basicfuns.jl
Breaking: prevent the doc string from promising the exact current implementation, to enable possible accuracy improvements in the future.
Updates #102
=> relax the doc string of `log2mexp`

src/basicfuns.jl, test/basicfuns.jl, test/common/ULPError.jl, test/runtests.jl
=> fix accuracy of `logcosh(::Union{Float16, Float32, Float64})`
